[versions]
accompanist-permissions = "0.37.3"
advanced-bottomsheet-material3 = "0.1.0"
android-gradle-plugin = "8.13.1"
android-maps-compose = "6.12.2"
android-maps-ktx = "5.2.1"
android-mapsplatform-secrets = "2.0.1"
android-places = "5.0.0"
androidx-activity = "1.12.0-rc01"
androidx-browser = "1.10.0-alpha02"
androidx-compose-bom = "2025.11.00"
androidx-compose-material3 = "1.5.0-alpha08"
androidx-core-ktx = "1.17.0"
androidx-core-splashscreen = "1.2.0"
androidx-datastore = "1.2.0-rc01"
androidx-glance = "1.2.0-beta01"
androidx-hilt = "1.3.0"
androidx-lifecycle = "2.10.0"
androidx-navigation3 = "1.0.0-rc01"
androidx-sqlite = "2.6.1"
androidx-test-core = "1.7.0"
androidx-test-espresso-core = "3.7.0"
androidx-test-ext-junit = "1.3.0"
androidx-work = "2.11.0"
apache-commons-lang = "3.20.0"
archunit = "1.4.1"
cache4k = "0.14.0"
coil = "3.3.0"
detekt = "2.0.0-alpha.1"
detekt-rules-compose = "0.4.27"
firebase = "34.6.0"
firebase-app-distribution-gradle-plugin = "5.2.0"
firebase-crashlytics-gradle-plugin = "3.0.6"
google-services = "4.4.4"
hilt = "2.57.2"
indriya = "2.2.3"
junit-jupiter = "6.0.1"
kotlin = "2.2.21"
kotlinx-coroutines-play-services = "1.10.2"
kotlinx-serialization = "1.9.0"
kover = "0.9.3"
ksp = "2.3.2"
ktor = "3.3.2"
ktorfit = "2.6.4"
mockk = "1.14.6"
play-services-location = "21.3.0"
play-services-maps = "19.2.0"
protobuf = "4.33.1"
protobuf-gradle-plugin = "0.9.5"
room = "2.8.3"
sqlcipher-android = "4.11.0"
timber = "5.0.1"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }

# androidx.compose
# https://developer.android.com/develop/ui/compose/bom/bom-mapping
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-runtime-annotation = { module = "androidx.compose.runtime:runtime-annotation" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-text-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }

advanced-bottomsheet-material3 = { module = "io.morfly.compose:advanced-bottomsheet-material3", version.ref = "advanced-bottomsheet-material3" }

# androidx.navigation3
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "androidx-navigation3" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "androidx-navigation3" }

# androidx.lifecycle
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "androidx-lifecycle" }

# androidx.test
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test-core" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso-core" }

# Google Play Services
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "play-services-location" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines-play-services" }

# Ktor
ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging" }

# Ktorfit
ktorfit-lib-light = { module = "de.jensklingenberg.ktorfit:ktorfit-lib-light", version.ref = "ktorfit" }

# Coil
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
coil-network-cache-control = { module = "io.coil-kt.coil3:coil-network-cache-control", version.ref = "coil" }
coil-test = { module = "io.coil-kt.coil3:coil-test", version.ref = "coil" }

# Google Maps SDK
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "play-services-maps" }
android-maps-ktx = { module = "com.google.maps.android:maps-ktx", version.ref = "android-maps-ktx" }
android-maps-utils-ktx = { module = "com.google.maps.android:maps-utils-ktx", version.ref = "android-maps-ktx" }
android-maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "android-maps-compose" }
android-maps-compose-utils = { module = "com.google.maps.android:maps-compose-utils", version.ref = "android-maps-compose" }
android-places = { module = "com.google.android.libraries.places:places", version.ref = "android-places" }

# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-crashlytics-ndk = { module = "com.google.firebase:firebase-crashlytics-ndk" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }

cache4k = { module = "io.github.reactivecircus.cache4k:cache4k", version.ref = "cache4k" }
apache-commons-lang = { module = "org.apache.commons:commons-lang3", version.ref = "apache-commons-lang" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist-permissions" }
indriya = { module = "tech.units:indriya", version.ref = "indriya" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-jupiter" }
archunit = { module = "com.tngtech.archunit:archunit", version.ref = "archunit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

# kotlinx-serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# Hilt
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android-runtime = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidx-hilt" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidx-hilt" }

# DataStore
protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
protobuf-kotlin-lite = { module = "com.google.protobuf:protobuf-kotlin-lite", version.ref = "protobuf" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "androidx-datastore" }

# Room
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
sqlcipher-android = { module = "net.zetetic:sqlcipher-android", version.ref = "sqlcipher-android" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "androidx-sqlite" }

# Glance
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "androidx-glance" }
androidx-glance-appwidget-preview = { group = "androidx.glance", name = "glance-appwidget-preview", version.ref = "androidx-glance" }
androidx-glance-appwidget-testing = { module = "androidx.glance:glance-appwidget-testing", version.ref = "androidx-glance" }
androidx-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "androidx-glance" }
androidx-glance-preview = { group = "androidx.glance", name = "glance-preview", version.ref = "androidx-glance" }
androidx-glance-testing = { module = "androidx.glance:glance-testing", version.ref = "androidx-glance" }

# WorkManager
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "androidx-work" }

# detekt
detekt-rules-ktlint-wrapper = { module = "dev.detekt:detekt-rules-ktlint-wrapper", version.ref = "detekt" }
detekt-rules-compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detekt-rules-compose" }

# for convention plugins
android-application-gradle-plugin = { module = "com.android.application:com.android.application.gradle.plugin", version.ref = "android-gradle-plugin" }
kotlin-android-gradle-plugin = { module = "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin", version.ref = "kotlin" }
kotlin-compose-gradle-plugin = { module = "org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin", version.ref = "kotlin" }
kotlin-serialization-gradle-plugin = { module = "org.jetbrains.kotlin.plugin.serialization:org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlin" }
ksp-gradle-plugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
hilt-gradle-plugin = { module = "com.google.dagger.hilt.android:com.google.dagger.hilt.android.gradle.plugin", version.ref = "hilt" }
protobuf-gradle-plugin = { module = "com.google.protobuf:protobuf-gradle-plugin", version.ref = "protobuf-gradle-plugin" }
room-gradle-plugin = { module = "androidx.room:androidx.room.gradle.plugin", version.ref = "room" }
ktorfit-gradle-plugin = { module = "de.jensklingenberg.ktorfit:de.jensklingenberg.ktorfit.gradle.plugin", version.ref = "ktorfit" }
detekt-gradle-plugin = { module = "dev.detekt:dev.detekt.gradle.plugin", version.ref = "detekt" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-gradle-plugin" }
firebase-app-distribution = { id = "com.google.firebase.appdistribution", version.ref = "firebase-app-distribution-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-gradle-plugin" }
room = { id = "androidx.room", version.ref = "room" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
android-mapsplatform-secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "android-mapsplatform-secrets" }

convention-android-compose-application = { id = "blue.starry.mitsubachi.buildlogic.convention.android.compose.application" }
convention-android-library = { id = "blue.starry.mitsubachi.buildlogic.convention.android.library" }
convention-android-compose-library = { id = "blue.starry.mitsubachi.buildlogic.convention.android.compose.library" }
convention-android-glance-library = { id = "blue.starry.mitsubachi.buildlogic.convention.android.glance.library" }
convention-detekt = { id = "blue.starry.mitsubachi.buildlogic.convention.detekt" }
convention-hilt = { id = "blue.starry.mitsubachi.buildlogic.convention.hilt" }
convention-kotlin-serialization = { id = "blue.starry.mitsubachi.buildlogic.convention.kotlin.serialization" }
convention-datastore = { id = "blue.starry.mitsubachi.buildlogic.convention.datastore" }
convention-room = { id = "blue.starry.mitsubachi.buildlogic.convention.room" }
convention-ktorfit = { id = "blue.starry.mitsubachi.buildlogic.convention.ktorfit" }
