name: Enable Auto-Merge

on:
  pull_request:
    types:
      - opened
      - ready_for_review

permissions: { }

jobs:
  enable-auto-merge:
    if: github.event.pull_request.user.login == 'SlashNephy' || github.actor == 'SlashNephy'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - run: gh pr merge --merge --auto "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.SLASHNEPHY_GITHUB_TOKEN }}
        continue-on-error: true
