name: Enable Auto-Merge

on:
  pull_request:
    types:
      - ready_for_review

jobs:
  enable-auto-merge:
    if: github.event.pull_request.user.login == 'SlashNephy'
    runs-on: ubuntu-latest
    steps:
      - run: gh pr merge --merge --auto "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.SLASHNEPHY_GITHUB_TOKEN }}
